---
- include: RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags: system-update

- include: Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags: system-update

- include: Debian.yml
  when: ansible_distribution == 'Debian'
  tags: system-update
